management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  devtools:
    remote:
      secret: "learning-spring-boot"

logging:
  level:
    com:
      pzeya: "DEBUG"
    org:
      sprintframework:
        data: "TRACE"
    reactor:
      core: "TRACE"
      util: "TRACE"
